# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassifiedsiOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClassifiedsiOSApp
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'


  target 'ClassifiedsiOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClassifiedsiOSAppUITests' do
    # Pods for testing
  end

end
